version: v2

tasks:
  build:
    steps:
    - checkout
    - cache/pull: pip-deps-{{ checksum "requirements.txt" }}
    - commands: 
      - python -c 'import site; print(site.getsitepackages())'
      - pip install -r requirements.txt
    - commands:
      - python test.py
    - cache/push: 
        key: pip-deps-{{ checksum "requirements.txt" }}
        paths:
        # need to change based on default python version
        # Please check https://docs.razorops.com/pipeline/linux-vm/tools/#python
        - ~/.pyenv/versions/3.9.9/lib/python3.9/site-packages
    - reports/junit: test-reports/*.xml
