
tasks:
  pyhton-sonar-job:
    runner: sonarsource/sonar-scanner-cli
    steps:
   
    - checkout    
    - commands:
      - |
       sonar-scanner \
        -Dsonar.projectKey=python-flask \
        -Dsonar.sources=. \
        -Dsonar.host.url=https://01ee-115-241-195-210.ngrok.io \
        -Dsonar.login=635976c20890cf92069b6f21343949f4325e2637
        
        
        
 
      
        
